language: node_js

node_js:
  - '6.0'

addons:
  firefox: 'latest'

env:
  - BROWSER=PhantomJS
  - BROWSER=ChromeTravisCI
  - BROWSER=Firefox

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g npm@latest
  - npm install -g bower karma-cli grunt-cli
  - bower install --force-latest
  - npm install

script:
  - cp config.sample.js config.js
  - grunt
  - npm test -- --browsers $BROWSER

after_success:
  - grunt coveralls
