language: node_js

node_js:
  - '8.0'

addons:
  firefox: 'latest'

env:
  - BROWSER=PhantomJS
  - BROWSER=ChromeTravisCI
  - BROWSER=Firefox

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - yarn install

script:
  - cp config.sample.js config.js
  - yarn grunt
  - yarn test --browsers $BROWSER

after_success:
  - yarn grunt coveralls
